In [36]:
import torch

# a=torch.arange(12).reshape(3,-1)
# a=torch.randn(3,4)
a=torch.tensor([[1,2,3],[2,3,4]])
b=torch.tensor([[2,2,3]])
print(a)
print(b)
print(a+b)
z=torch.zeros_like(b)
y=torch.ones_like(a)
print(z)
print(z.numpy)
a>=b
# c=torch.cat((a,b),dim=1)
# print(c)
# print(c.sum())
# print(a.numel())
# print(a.shape)
# print(a.size())


tensor([[1, 2, 3],
        [2, 3, 4]])
tensor([[2, 2, 3]])
tensor([[3, 4, 6],
        [4, 5, 7]])
tensor([[0, 0, 0]])
<built-in method numpy of Tensor object at 0x0000026F13F64180>


tensor([[False,  True,  True],
        [ True,  True,  True]])